name: ci

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Say Hello to the World!
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.x

      - name: Install Dependencies
        run: yarn --frozen-lockfile --prefer-offline

      - name: Run Jest tests
        run: yarn test
