name: ci

on:
  pull_request:

  jobs:
    build:
      runs-on: ubuntu-latest

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      steps:
        - name: Say Hello to the World!
          run: echo 'Hello World!'
